spring:
  application:
    name: hugegraph-pd

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: 'file:./conf/log4j2.xml'
license:
  verify-path: ./conf/verify-license.json
  license-path: ./conf/hugegraph.license
grpc:
  # 集群模式
  port: 8686
  # host: 10.21.3.15
  ############################################################################ 【本地测试】
  host: 127.0.0.1

server:
  # rest 服务端口号
  port: 8620

pd:
  # 存储路径
  # data-path: ./pd_data
  # 自动扩容的检查周期，定时检查每个 store 的分区数量，自动进行分区数量平衡
  patrol-interval: 1800
  # 初始 store 列表，在列表内的 store 自动激活
  initial-store-count: 1
  # grpc IP:grpc port
  initial-store-list: 10.21.3.15:8500,10.21.3.16:8500,10.21.3.17:8500
  ############################################################################ 【本地测试】
  data-path: ./pd_data_15

raft:
  # 集群模式
  # address: 10.21.3.15:8610
  # peers-list: 10.21.3.15:8610,10.21.3.16:8610,10.21.3.17:8610
  ############################################################################ 【本地测试】
  address: 127.0.0.1:8610
  peers-list: 127.0.0.1:8610,127.0.0.1:8611,127.0.0.1:8613

store:
  # store 下线时间。超过该时间，认为 store 永久不可用，分配副本到其他机器，单位秒
  max-down-time: 172800
  # 是否开启 store 监控数据存储
  monitor_data_enabled: true
  # 监控数据的间隔，minute (默认), hour, second
  # default: 1 min * 1 day = 1440
  monitor_data_interval: 1 minute
  # 监控数据的保留时间 1 天; day, month, year
  monitor_data_retention: 1 day
  initial-store-count: 1

partition:
  # 默认每个分区副本数
  default-shard-count: 1
  # 默认每机器最大副本数，初始分区数 = store-max-shard-count * store-number / default-shard-count
  store-max-shard-count: 12
