pdserver:
  # pd服务地址，多个pd地址用逗号分割
  address: localhost:8686
grpc:
  # grpc的服务地址
  host: 127.0.0.1
  port: 8500
  netty-server:
    max-inbound-message-size: 1000MB
raft:
  # raft 缓存队列大小
  disruptorBufferSize: 1024
  address: 127.0.0.1:8510
  max-log-file-size: 600000000000
  # 快照生成时间间隔，单位秒
  snapshotInterval: 1800
server:
  # rest 服务地址
  port: 8520

app:
  # 存储路径，支持多个路径，逗号分割
  data-path: ./storage

spring:
  application:
    name: store-node-grpc-server

logging:
  config: 'file:./conf/log4j2.xml'
  level:
    root: info

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

rocksdb:
  # rocksdb使用的总内存大小,达到该值强制写盘
  total_memory_size: 32000000000
  # rocksdb使用的memtable大小
  write_buffer_size: 32000000
  # 对于每个rocksdb来说，memtable个数达到该值进行写盘
  min_write_buffer_number_to_merge: 16
