pdserver:
  # pd服务地址，多个pd地址用逗号分割
  address: localhost:8686

grpc:
  # grpc的服务地址
  host: 127.0.0.1
  port: 8500
  netty-server:
    max-inbound-message-size: 1000MB
raft:
  address: 127.0.0.1:8510
  max-log-file-size: 600000000000
  # 快照生成时间间隔，单位秒
  snapshotInterval: 1800
server:
  # rest 服务地址
  port: 8520

app:
  # 存储路径，支持多个路径，逗号分割
  data-path: ./storage

spring:
  profiles:
    active: default
    include: pd
  application:
    name: store-node-grpc-server

logging:
  config: classpath:log4j2-dev.xml
  level:
    root: info
