spring:
  application:
    name: hugegraph-pd
logging:
  config: 'file:./conf/log4j2.xml'

grpc:
  port: 8686
  # grpc的服务地址, 部署时需要改为本地实际IPv4地址。
  host: 127.0.0.1

server:
  # rest服务端口号
  port: 8620

pd:
  # 存储路径
  data-path: ./pd_data
  # 自动扩容的检查周期，定时检查每个Store的分区数量，自动进行分区数量平衡
  patrol-interval: 1800
  enable-batch-load: false
  initial-store-count: 1
  # 初始store列表，grpc IP:grpc port, 在列表内的store自动激活
  initial-store-list: 127.0.0.1:8500
raft:
  # 本机raft服务地址
  address: 127.0.0.1:8610
  # PD集群服务地址
  peers-list: 127.0.0.1:8610

store:
  # store下线时间。超过该时间，认为store永久不可用，分配副本到其他机器，单位秒
  max-down-time: 172800
partition:
  # 默认每个分区副本数
  default-shard-count: 1
  # 默认每机器最大副本数,初始分区数= store-max-shard-count * store-number / default-shard-count
  store-max-shard-count: 12

